// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Elders.Cronus.Projections.Cassandra")]
[assembly: AssemblyDescriptionAttribute("Cronus.Projections.Cassandra")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyProductAttribute("Elders.Cronus.Projections.Cassandra")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2016")]
[assembly: AssemblyVersionAttribute("1.1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.1.0-beta.3+5.Branch.release-1.1.0.Sha.9cd0a2a91e1a015874c408e8bf31dd0fda019beb")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.1.0.0";
    }
}
